name: 7-10-playground

services:
  config_server:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: config_server
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27019" ]
      interval: 5s
      start_period: 10s

  init_mongo_cluster:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: init_cluster
    entrypoint: >
      bash -c "

      echo 'Waiting for the config server to respond...';
      until mongosh --host config_server --port 27019 --eval 'db.adminCommand({ping:1})' &>/dev/null; do
        sleep 2;
      done;
      echo 'Initializing the replica set...';
      mongosh --host config_server --port 27019 --eval '
        rs.initiate({
          _id: \"config_server\",
          configsvr: true,
          version: 1,
          members: [
            { _id: 0, host: \"config_server:27019\" }
          ]
        })
      ';
      echo 'Replica set configuration completed successfully!';

      echo 'Waiting for the shard-NL-1 server to respond...';
      until mongosh --host shard-NL-1 --port 27018 --eval 'db.adminCommand({ping:1})' &>/dev/null; do
        sleep 2;
      done;
      echo 'Waiting for the shard-NL-2 server to respond...';
      until mongosh --host shard-NL-2 --port 27018 --eval 'db.adminCommand({ping:1})' &>/dev/null; do
        sleep 2;
      done;
      echo 'Initializing shard-NL-1...';
      mongosh --host shard-NL-1 --port 27018 --eval '
        rs.initiate({
          _id : \"shard-NL-1\",
          members: [
            { _id : 0, host : \"shard-NL-1:27018\" }
          ]
        })
      ';
      echo 'shard-NL-1 configuration completed successfully!';
      echo 'Initializing shard-NL-2...';
      mongosh --host shard-NL-2 --port 27018 --eval '
        rs.initiate({
          _id : \"shard-NL-2\",
          members: [
            { _id : 0, host : \"shard-NL-2:27018\" }
          ]
        })
      ';
      echo 'shard-NL-2 configuration completed successfully!';

      echo 'Waiting for the shard-RU-1 server to respond...';
      until mongosh --host shard-RU-1 --port 27018 --eval 'db.adminCommand({ping:1})' &>/dev/null; do
        sleep 2;
      done;
      echo 'Waiting for the shard-RU-2 server to respond...';
      until mongosh --host shard-RU-2 --port 27018 --eval 'db.adminCommand({ping:1})' &>/dev/null; do
        sleep 2;
      done;
      echo 'Initializing shard-RU-1...';
      mongosh --host shard-RU-1 --port 27018 --eval '
        rs.initiate({
          _id : \"shard-RU-1\",
          members: [
            { _id : 0, host : \"shard-RU-1:27018\" }
          ]
        })
      ';
      echo 'shard-RU-1 configuration completed successfully!';
      echo 'Initializing shard-RU-2...';
      mongosh --host shard-RU-2 --port 27018 --eval '
        rs.initiate({
          _id : \"shard-RU-2\",
          members: [
            { _id : 0, host : \"shard-RU-2:27018\" }
          ]
        })
      ';
      echo 'shard-RU-2 configuration completed successfully!';

      echo 'Waiting for the router server to respond...';
      until mongosh --host mongos_router --port 27017 --eval 'db.adminCommand({ping:1})' &>/dev/null; do
        sleep 2;
      done;
      echo 'Initializing shards...';
      mongosh --host mongos_router --port 27017 --eval '
        sh.addShard(\"shard-NL-1/shard-NL-1:27018\");
        sh.addShard(\"shard-NL-2/shard-NL-2:27018\");
        sh.addShard(\"shard-RU-1/shard-RU-1:27018\");
        sh.addShard(\"shard-RU-2/shard-RU-2:27018\");

        sh.enableSharding(\"playground\");
      ';
      echo 'shards configuration completed successfully!';

      touch /var/run/cluster-init

      while true; do
        sleep 86400
      done

      "
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    healthcheck:
      test: [ "CMD", "test", "-f", "/var/run/cluster-init" ]
      interval: 5s
      start_period: 10s
      retries: 500

  shard-NL-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard-NL-1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    volumes:
      - shard-NL-1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard-NL-1",
        "--bind_ip_all",
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

  shard-NL-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard-NL-2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.13
    volumes:
      - shard-NL-2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard-NL-2",
        "--bind_ip_all",
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

  shard-RU-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard-RU-1
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.18
    volumes:
      - shard-RU-1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard-RU-1",
        "--bind_ip_all",
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

  shard-RU-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard-RU-2
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    volumes:
      - shard-RU-2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard-RU-2",
        "--bind_ip_all",
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s
 
  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router
    restart: always
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos",
        "--configdb", 
        "config_server/config_server:27019",
        "--bind_ip_all",
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27017" ]
      interval: 5s
      start_period: 10s
      retries: 500

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data:
  shard-NL-1-data:
  shard-NL-2-data:
  shard-RU-1-data:
  shard-RU-2-data:



